Fix alias error due to numpy update（meta.py）
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

It says:
`np.bool` was a deprecated alias for the builtin `bool`.
To avoid this error in existing code, use bool by itself.
Doing this will not modify any behavior and is safe.
If specifically wanted the numpy scalar type, use `np.bool_` here.

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations